meta_product_name: "Planneed"
meta_title: "Planneed - Pour un meilleur accompagnement et gestion des heures supplémentaires à l'hôpital."
meta_description: "Révolutionne la gestion des hôpitaux et facilite le travail des soignants"
meta_image: "cover.png" # should exist in `app/assets/images/`
